### ISSUE TITLE
Instalação e setup do sistema

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#1]
- [x] Instalar git no Windows
- [x] Clonar o repositório
- [x] Instalar nvm no Windows
- [x] Instalar yarn no Windows
- [ ] .....

**Comment by lucastonussi** [comment]
- [x] exemplo de tarefas completas
- [x] outra
- [x] outra
- [ ] ......

**Comment by lucastonussi** [comment]
- [x] Marina completou `git status`

**Comment by lucastonussi** [comment]
- [x] Abriu projeto no vscode
- [x] Aprendeu a abrir terminal git no vscode
- [x] Aprendeu a splitar terminal
- [ ] ....

**Comment by lucastonussi** [comment]
- [x] Aprendeu a abrir o terminal node no vscode

**Comment by lucastonussi** [comment]
- [x] Aprendeu glossário básico sobre npm, nvm, node
- [x] Aprendeu a usar básico do yarn, yarn run dev
- [x] Aprendeu a entrar no link gerado do web app para desenvolver localmente

**Comment by lucastonussi** [comment]
- [x] Viu video aula no Loom
- [x] Aprendeu comandos bem simples do git para adicionar suas mudanças

```sh
git checkout -b marina # só precisa digitar isso 1x apenas

# isso se repete para cada mudança
git add <caminho até o arquivo>
git commit <caminho até o arquivo> -m 'Altera layout'

# isso vc faz sempre que quiser enviar suas mudanças para que todos do projeto possam ver
git push origin marina
```

**Comment by lucastonussi** [comment]
- [x] Viu placeholders de imagens dos gatinhos https://placekitten.com/
- [ ] Usou o placeholder (se quiser) como imagem na tela
- [x] Programou a tela com novo layout (simples)
- [ ] Viu as tasks em "para fazer" e completou elas
- [x] Usou os comandos do git depois de terminar tudo

```sh

git checkout -b marina # só precisa digitar isso 1x apenas

# isso se repete para cada mudança
git add <caminho até o arquivo>
git commit <caminho até o arquivo> -m 'Altera layout'

# isso vc faz sempre que quiser enviar suas mudanças para que todos do projeto possam ver
git push origin marina

```

**Comment by lucastonussi** [comment]
@marinamq ☝

**Comment by marinamq** [comment]
ok
