### ISSUE TITLE
Adicionar traduções

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#11]
Vá até os arquivoS dentro de **locales**

Haverá um conteúdo como esse:

```json
{
  "greeting": "olá, {name}",
  "generals": {
    "toolbar": {
      "left": {
        "discovery": "Descoberta"
      }
    }
  }
}
```

O que tens que fazer para todos os arquivos é colocar as chaves e traduções que faltam,
depois é só abrir PR.

Mas lembrar de verificar se no app localhost está traduzindo corretamente.

No rodapé tem um switch para trocar de lingua.

**Comment by marinamq** [comment]
Está traduzindo corretamente. Aberto o PR.
