### ISSUE TITLE
Proponha um design melhor

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#13]
Proponha um desenho de um design de layout que melhore a usabilidade para a tela abaixo

Essa tela a proposta dela é de ser um painel de opções para se chegar até informações mais detalhadas, é uma tela que roteia o usuário para categorias diferentes.

![Image](https://user-images.githubusercontent.com/110938532/188965714-62387d68-8699-4ff0-86fa-9dd7e272bf41.png)

- [x] proposta de design (pode ser um desenho no papel)
- [ ] implementar esse design (usando html, css)

Para implementar o design basta mexer apenas no arquivo pages/discover.vue

```
# vai para branch main
git checkout main

# traz tudo de novo
git pull origin main

# cria nova branch, partindo da branch main
git checkout -b novo-design-discovery

# adiciona suas mudanças
git add pages/discover.vue
git commit pages/discover.vue -m 'Add novo layout'
git push origin novo-design-discovery

# abra pr para avaliação
```

**Comment by lucastonussi** [comment]
- [x] da uma olhada nessas opções https://vuetifyjs.com/en/components/cards/#loading
- [x] faz uma conta no https://miro.com/pt/login/
- [x] da para desenhar lá e esquematizar

**Comment by marinamq** [comment]
Já tenho conta no miro, usei ele pra fazer fluxograma no curso de desenvolvedor.

**Comment by lucastonussi** [comment]
Exemplo para pensar:

- [x] https://analisa.genialinvestimentos.com.br/carteiras-recomendadas/fundos-imobiliarios



![Image](https://user-images.githubusercontent.com/110938532/190658291-d682ccf6-3e05-4245-af38-d5329c5638bd.png)

**Comment by marinamq** [comment]
Seria algo do tipo?

![proposta design](https://user-images.githubusercontent.com/109256347/191012976-2f2a58a0-03a7-44c9-b5db-d0f9a2106d32.jpg)

**Comment by lucastonussi** [comment]
Parece interessando e gostei, acho que a coluna da direita pode entrar como um alt no card

https://www.w3schools.com/tags/att_img_alt.asp
