### ISSUE TITLE
Criar um caso de uso

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#17]
Temos uma tela dessa maneira

![Image](https://user-images.githubusercontent.com/110938532/193824955-b83aed04-e412-4f80-b4bc-2c75a37c49bf.png)

Mas queremos melhorar essa tela dando valor para ela.

Então existem vários caminhos para criar algo para cães de estimação... vamos tentar fazer um petshop online:

# Missão

Ler esse post https://www.nuvemshop.com.br/blog/como-abrir-um-pet-shop-online/

E extrair 3 necessidades que um petshop precisa e escrever estas 3 necessidades **QUE O APP/SITE PRECISA**, e colocar no diagrama de caso de uso abaixo:

Tentar responder a pergunta: "O que um petshop online precisa" ?
1)
2)
3)

https://drive.google.com/file/d/1owWT6rg6yukMvpIg_4_jEGG5-ZemFt23/view?usp=sharing

![Image](https://user-images.githubusercontent.com/110938532/193829696-7f26f52c-e5bd-4727-a782-baf91ba8bfcf.png)

**Comment by marinamq** [comment]
Acho que é isso. Fiz um pensando em relação ao que o petshop tem a oferecer, e outro de coisas que são necessárias de "estrutura" do site.

![Image](https://user-images.githubusercontent.com/109256347/195214406-d68b3b61-1dd8-4d7c-a06f-30f70f2e0901.jpg)

**Comment by lucastonussi** [comment]
Legal, ficou bom.
