### ISSUE TITLE
Estudar e implementar datatime-local

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#18]
# Missão

Primeiro ler sobre datatime-local https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

# Depois

Depois que ler tentar implementar o date, semelhante como foi feito o slider.

O Slider que na verdade é um tipo de Input em html, ele é um número um valor, que você pode mexer no slider e alterar esse valor mais facilmente.

![Image](https://user-images.githubusercontent.com/110938532/194154433-0dcf6688-a937-4f2a-b615-73463bf76334.png)

Por exemplo queremos implementar isso, pode ser abaixo do slider...

![Image](https://user-images.githubusercontent.com/110938532/194154723-00d01bfd-09ab-4451-b162-bb43f0690fe1.png)

Qualquer dúvida, comente.

![Image](https://user-images.githubusercontent.com/110938532/194154633-325d8709-a336-47fd-91bd-a6b761a8ee0a.png)

**Comment by marinamq** [comment]
Enviado PR.

**Comment by lucastonussi** [comment]
Vou ver

**Comment by lucastonussi** [comment]
O seu código precisa de formatações no css

**Comment by lucastonussi** [comment]
Voltando para em progresso

**Comment by marinamq** [comment]
Corrigido.
