### ISSUE TITLE
Criar uma nova página chamada 'Fundos Imobiliários'

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#20]
# Missão

- A página pode ter dados fictícios, claro.
- Mas ela tem que ser semelhante a imagem abaixo.

![Image](https://user-images.githubusercontent.com/110938532/198379159-d398a0de-2d17-479b-b915-58e4d4f2bcaf.png)

- A rota da página pode ser bem simples /fiis por exemplo, ou algo como /fundos
- Note que basta você planejar 1 componente e os demais você replica

**Comment by marinamq** [comment]
Página feita e enviada para avaliação.
