### ISSUE TITLE
Criar um componente novo, que pode ser reutilizado onde quisermos

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#21]
# Missão

Criar um componenten reutilizável

Semelhante a imagem abaixo

![Image](https://user-images.githubusercontent.com/110938532/198709430-bc48ece0-77e7-40cb-adb6-c79e62464132.png)

Você deve fazer uma checklist das necessidades do componente, para implementar ele.

Imagens se quiser utilizar:

|upvote|funny|love|surprised|angry|sad|
|-|-|-|-|-|-|
| <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/sad-512x512.png"></img> | <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/angry-512x512.png"></img> | <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/surprised-512x512.png"></img> | <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/love-512x512.png"></img> | <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/funny-512x512.png"></img> | <img height='30' src="https://c.disquscdn.com/next/current/publisher-admin/assets/img/emoji/upvote-512x512.png"></img> |

**Comment by lucastonussi** [comment]
🌈

**Comment by lucastonussi** [comment]
🍏

**Comment by marinamq** [comment]
Added component and used it on Fundos.
