### ISSUE TITLE
Projeto do app de adoções

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#24]
# Produto

- Idealização do produto
- Fazer um diagrama desses no Miro
- Fazer esses diagrama (faz, não faz, etc) para o produto do app das adoções de cães

![Image](https://user-images.githubusercontent.com/110938532/199793293-426c1aad-b714-482f-9d2d-00d11211239a.png)

- Link miro https://miro.com/welcomeonboard/UVNqVGFFZGxieHJ0SHp2dGhRdk5FOEpwalJqYWNKVW52Zmp5RFRvVGtWM3N1OHFpQlM3Qlp0QjlTeTliMVdjRHwzMDc0NDU3MzQ5MDEyMzAwMzE4fDI=?share_link_id=772328243977

**Comment by marinamq** [comment]
https://miro.com/app/board/uXjVPVPi6mM=/

**Comment by marinamq** [comment]
![Image](https://user-images.githubusercontent.com/109256347/221178540-1eb0bbe5-dd80-4125-a599-c85f4f1ce69b.png)
